spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9093
      bindings:
        loginTopic-update-from-login-legacy-service:
          destination: loginTopic
          contentType: application/json
        loginTopic-update-from-login-service:
          destination: loginTopic
          contentType: application/json
server:
     port: 8889        
