spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9093
      bindings:
        login-update-from-loginLegacyTopic:
          destination: loginLegacyTopic
          contentType: application/json
        login-update-for-loginTopic:
          destination: loginTopic
          contentType: application/json
server:
     port: 8889   
